/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import chat.Usuario;
import javax.swing.JTextArea;
import red.Cliente;
import red.Servidor;

/**
 *
 * @author luiss
 */
public class Principal extends javax.swing.JFrame {
    Inicio vInicio;
    //Usuario usuario;
    //String ipServidor;
    //int puertoServidor;
    
    //JTextArea txta_listaMensajes;
    
    Cliente cliente;
    /**
     * Creates new form Principal
     */
    
    public Principal() {        
        initComponents();
    }
    
    //public Principal(String usuario, String ipS, int puertoS, Inicio vInicio) {
    public Principal(Cliente cliente, Inicio vInicio) {
        this.vInicio = vInicio;
        
        //this.usuario = new Usuario(usuario);
        
        /*this.ipServidor = ipS;
        this.puertoServidor = puertoS;
        
        cliente = new Cliente();
        cliente.iniciarConexion(ipServidor, puertoServidor);
        cliente.loginUsuario(this.usuario);*/
        
        this.cliente = cliente;
        initComponents();
        
        servicioCliente.start();
    }
    
    //Hilo para recepción de mensajes
    Thread servicioCliente = new Thread(
            new Runnable() {
                @Override
                public void run() {
                    try {
                        String[] mensajeDelServidor = new String[2];
                        while (true) {                            
                            String mensaje = cliente.recibirMensaje();
                            mensajeDelServidor = cliente.analizarMensajeServidor(mensaje);
                            
                            if (mensajeDelServidor[0].equals("OK")) {
                                cargarTexto(mensajeDelServidor[1]);
                            } else {
                            }
                            
                        }
                        
                    } catch (Exception e) {
                    }
                }
            }
        );
    
    public void cargarTexto(String texto){
        this.txta_listaMensajes.append(texto+"\n");
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txta_listaMensajes = new javax.swing.JTextArea();
        txt_mensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txta_listaMensajes.setColumns(20);
        txta_listaMensajes.setRows(5);
        jScrollPane1.setViewportView(txta_listaMensajes);

        btnEnviar.setText("Enviar");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_mensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        // TODO add your handling code here:
        String mensaje = txt_mensaje.getText();
        cliente.enviarSolicitud("MSG",mensaje);
        txt_mensaje.setText("");
        cargarTexto(mensaje);
    }//GEN-LAST:event_btnEnviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_mensaje;
    private javax.swing.JTextArea txta_listaMensajes;
    // End of variables declaration//GEN-END:variables
}
